"""Default config values, built-in presets, and key groups."""

from __future__ import annotations

from typing import Any, Dict, Tuple

APP_NAME = "Velo"
APP_VERSION = "2.1.1"
PRESET_CLIP_PREFIX = "VELO1."
PRESET_CLIP_PREFIX_V2 = "VELO2."

PRESET_EXCLUDE = frozenset(
    {
        "host",
        "port",
        "auth_token",
        "auth_enabled",
        "ui_preview_mode",
        "ui_section",
        "ui_obs_setup_done",
        "start_minimized",
        "open_settings_on_start",
        "start_with_windows",
        "update_check_mode",
        "active_preset",
        "active_preset_kind",
        "stats_reset_hotkey",
        "stats_dpi",
        "stats_update_rate",
        "show_onboarding",
        "hud_show_sparkline",
        "accent_color",
        "bg_color",
        "hidden_presets",
        "backup_enabled",
        "backup_max_count",
    }
)

SHELL_KEYS = frozenset(
    {
        "host",
        "port",
        "auth_token",
        "auth_enabled",
        "ui_preview_mode",
        "ui_section",
        "ui_obs_setup_done",
        "start_minimized",
        "open_settings_on_start",
        "start_with_windows",
        "update_check_mode",
        "stats_reset_hotkey",
        "stats_dpi",
        "stats_update_rate",
        "show_onboarding",
        "accent_color",
        "bg_color",
        "hidden_presets",
    }
)

STATS_UPDATE_HZ = {
    "slow": 2.0,
    "normal": 4.0,
    "fast": 10.0,
}

FEEL_PRESETS: Dict[str, Dict[str, Any]] = {
    "tight": {
        "motion_scale": 1.4,
        "motion_ease": 0.08,
        "camera_lag": 0.05,
    },
    "normal": {
        "motion_scale": 1.0,
        "motion_ease": 0.2,
        "camera_lag": 0.15,
    },
    "soft": {
        "motion_scale": 0.55,
        "motion_ease": 0.45,
        "camera_lag": 0.3,
    },
}

QUALITY_PRESETS: Dict[str, Dict[str, Any]] = {
    "performance": {
        "target_fps": 60,
        "trail_max_points": 80,
        "trail_samples": 1,
        "trail_curve": 0.0,
        "trail_glow": False,
        "trail_smoothing": 0.0,
        "trail_lifetime_ms": 600,
        "ws_send_hz": 90,
    },
    "balanced": {
        "target_fps": 60,
        "trail_max_points": 120,
        "trail_samples": 2,
        "trail_curve": 0.55,
        "trail_glow": True,
        "trail_glow_blur": 6,
        "trail_glow_opacity": 1.0,
        "trail_glow_width": 1.0,
        "trail_glow_custom_color": False,
        "trail_glow_custom_color_val": "#ffffff",
        "trail_smoothing": 0.0,
        "trail_lifetime_ms": 750,
        "ws_send_hz": 120,
    },
    "pretty": {
        "target_fps": 90,
        "trail_max_points": 200,
        "trail_samples": 4,
        "trail_curve": 0.85,
        "trail_glow": True,
        "trail_glow_blur": 12,
        "trail_glow_opacity": 1.0,
        "trail_glow_width": 1.0,
        "trail_glow_custom_color": False,
        "trail_glow_custom_color_val": "#ffffff",
        "trail_smoothing": 0.0,
        "trail_lifetime_ms": 900,
        "ws_send_hz": 180,
    },
}

DEFAULT_SPEED_STOPS = [
    {"t": 0.0, "color": "#ffffff"},
    {"t": 0.45, "color": "#a0a0a0"},
    {"t": 0.75, "color": "#ffcc66"},
    {"t": 1.0, "color": "#ff4444"},
]

PRESETS: Dict[str, Dict[str, Any]] = {
    "16:9 pad": {
        "canvas_aspect": "16:9",
        "canvas_width": 640,
        "canvas_height": 360,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_x_pct": 50,
        "pad_y_pct": 50,
        "pad_shape": "rounded",
        "pad_radius": 12,
        "pad_bg_enabled": True,
        "pad_bg_color": "#0a0a0a",
        "pad_bg_opacity": 0.72,
        "pad_border_enabled": True,
        "pad_border_color": "#ffffff",
        "pad_border_opacity": 0.12,
        "pad_grid": False,
        "pad_crosshair": True,
        "pad_vignette": False,
        "source_bg_enabled": False,
        "view_mode": "infinite",
    },
    "16:9 grid": {
        "canvas_aspect": "16:9",
        "canvas_width": 640,
        "canvas_height": 360,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_x_pct": 50,
        "pad_y_pct": 50,
        "pad_shape": "rect",
        "pad_radius": 0,
        "pad_bg_enabled": True,
        "pad_bg_color": "#000000",
        "pad_bg_opacity": 0.85,
        "pad_border_enabled": True,
        "pad_border_color": "#ffffff",
        "pad_border_opacity": 0.18,
        "pad_grid": True,
        "pad_grid_size": 40,
        "pad_grid_opacity": 0.08,
        "pad_crosshair": True,
        "pad_vignette": False,
        "source_bg_enabled": False,
        "view_mode": "infinite",
    },
    "Square HUD": {
        "canvas_aspect": "1:1",
        "canvas_width": 480,
        "canvas_height": 480,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_shape": "rounded",
        "pad_radius": 16,
        "pad_bg_enabled": True,
        "pad_bg_color": "#000000",
        "pad_bg_opacity": 0.65,
        "pad_border_enabled": True,
        "pad_border_opacity": 0.14,
        "pad_grid": False,
        "pad_crosshair": True,
        "view_mode": "infinite",
    },
    "Border only": {
        "canvas_aspect": "16:9",
        "canvas_width": 640,
        "canvas_height": 360,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_shape": "rounded",
        "pad_radius": 10,
        "pad_bg_enabled": False,
        "pad_border_enabled": True,
        "pad_border_color": "#ffffff",
        "pad_border_opacity": 0.22,
        "pad_shadow": False,
        "pad_grid": False,
        "pad_crosshair": True,
        "pad_vignette": False,
        "source_bg_enabled": False,
        "view_mode": "infinite",
    },
    "Transparent trails": {
        "canvas_aspect": "16:9",
        "canvas_width": 960,
        "canvas_height": 540,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_bg_enabled": False,
        "pad_border_enabled": False,
        "pad_shadow": False,
        "pad_grid": False,
        "pad_crosshair": False,
        "pad_vignette": False,
        "source_bg_enabled": False,
        "view_mode": "infinite",
    },
    "Corner mini": {
        "canvas_aspect": "16:9",
        "canvas_width": 400,
        "canvas_height": 225,
        "pad_width_pct": 100,
        "pad_height_pct": 100,
        "pad_shape": "rounded",
        "pad_radius": 8,
        "pad_bg_enabled": True,
        "pad_bg_color": "#000000",
        "pad_bg_opacity": 0.55,
        "pad_border_enabled": True,
        "pad_border_opacity": 0.15,
        "pad_crosshair": False,
        "view_mode": "infinite",
    },
}

DEFAULTS: Dict[str, Any] = {
    "host": "127.0.0.1",
    "port": 27180,
    "auth_token": "",
    "auth_enabled": True,
    "capture_mode": "relative",
    "invert_y": False,
    "sensitivity": 1.0,
    "view_mode": "infinite",
    "camera_lag": 0.15,
    "camera_look_ahead": 0.0,
    "camera_follow": 1.0,
    "view_zoom": 1.0,
    "motion_scale": 1.0,
    "motion_ease": 0.2,
    "motion_feel": "normal",
    "target_fps": 60,
    "render_quality": "balanced",
    "ws_send_hz": 120,
    "ui_preview_mode": "lite",
    "trail_enabled": True,
    "trail_lifetime_ms": 1100,
    "trail_max_points": 120,
    "trail_width": 2.4,
    "trail_glow": True,
    "trail_glow_blur": 6,
    "trail_glow_opacity": 1.0,
    "trail_glow_width": 1.0,
    "trail_glow_custom_color": False,
    "trail_glow_custom_color_val": "#ffffff",
    "trail_min_distance": 1.2,
    "trail_smoothing": 0.0,
    "trail_curve": 0.55,
    "trail_samples": 2,
    "fade_style": "smooth",
    "trail_color": "#ffffff",
    "speed_min": 40.0,
    "speed_max": 3200.0,
    "speed_stops": DEFAULT_SPEED_STOPS,
    "speed_colorize": True,
    "show_cursor_dot": True,
    "cursor_dot_size": 4.5,
    "cursor_dot_color": "#ffffff",
    "cursor_dot_opacity": 0.95,
    "show_clicks": True,
    "click_lifetime_ms": 280,
    "click_radius": 16.0,
    "click_line_width": 1.5,
    "click_opacity": 0.85,
    "click_expand": True,
    "click_style": "ring",
    "click_show": {
        "left": True,
        "right": True,
        "middle": True,
        "side": True,
    },
    "click_colors": {
        "left": "#ffffff",
        "right": "#cccccc",
        "middle": "#888888",
        "x1": "#aaaaaa",
        "x2": "#aaaaaa",
    },
    "pad_enabled": True,
    "pad_shape": "rounded",
    "pad_width_pct": 100,
    "pad_height_pct": 100,
    "pad_x_pct": 50,
    "pad_y_pct": 50,
    "pad_radius": 12,
    "pad_bg_enabled": True,
    "pad_bg_color": "#0a0a0a",
    "pad_bg_opacity": 0.72,
    "pad_blur": False,
    "pad_border_enabled": True,
    "pad_border_color": "#ffffff",
    "pad_border_opacity": 0.12,
    "pad_border_width": 1.5,
    "pad_shadow": False,
    "pad_shadow_opacity": 0.4,
    "pad_grid": False,
    "pad_grid_size": 40,
    "pad_grid_thickness": 1.0,
    "pad_grid_color": "#ffffff",
    "pad_grid_opacity": 0.08,
    "pad_crosshair": False,
    "pad_crosshair_color": "#ffffff",
    "pad_crosshair_opacity": 0.14,
    "pad_crosshair_size": 14,
    "pad_vignette": False,
    "pad_vignette_opacity": 0.3,
    "pad_clip_trail": True,
    "canvas_aspect": "16:9",
    "canvas_width": 640,
    "canvas_height": 360,
    "source_bg_enabled": False,
    "source_bg_color": "#000000",
    "source_bg_opacity": 0.0,
    "overlay_opacity": 1.0,
    "show_stats": False,
    "stats_opacity": 0.55,
    "stats_bg": True,
    "stats_border": True,
    "stats_x_pct": 0.0,
    "stats_y_pct": 100.0,
    "stats_show_speed": True,
    "stats_show_peak": False,
    "stats_show_cps": True,
    "stats_show_clicks": True,
    "stats_show_distance": True,
    "stats_units": "cm",
    "stats_dpi": 800,
    "stats_update_rate": "normal",
    "stats_reset_hotkey": "",
    "start_minimized": False,
    "open_settings_on_start": True,
    "start_with_windows": False,
    "update_check_mode": "launch",
    "ui_section": "presets",
    "ui_obs_setup_done": False,
    "active_preset": "16:9 pad",
    "active_preset_kind": "builtin",
    "show_onboarding": True,
    "hud_show_avg_speed": True,
    "hud_show_sparkline": True,
    "chart_color": "#a677ff",
    "accent_color": "#a277ff",
    "bg_color": "#0f0f0f",
    "hidden_presets": [],
    "backup_enabled": True,
    "backup_max_count": 10,
}

# Config key -> alias mapping for VELO2 share codes
# Dict sub-keys use ("parent", "sub") tuples
SHARE_ALIASES: Dict[str, Any] = {
    # Trail
    "trail_enabled": "te",
    "trail_lifetime_ms": "tl",
    "trail_max_points": "tx",
    "trail_width": "tw",
    "trail_glow": "tg",
    "trail_glow_blur": "tb",
    "trail_glow_opacity": "go",
    "trail_glow_width": "gw",
    "trail_glow_custom_color": "gc",
    "trail_glow_custom_color_val": "gcv",
    "trail_min_distance": "td",
    "trail_smoothing": "ts",
    "trail_curve": "tk",
    "trail_samples": "tn",
    "fade_style": "tf",
    "trail_color": "tc",
    "speed_colorize": "tz",
    "speed_max": "smx",
    "speed_min": "smn",
    "speed_stops": "sps",

    # Pad
    "pad_enabled": "pe",
    "pad_shape": "ph",
    "pad_width_pct": "pw",
    "pad_height_pct": "pht",
    "pad_x_pct": "px",
    "pad_y_pct": "py",
    "pad_radius": "pr",
    "pad_bg_enabled": "pbe",
    "pad_bg_color": "pbc",
    "pad_bg_opacity": "pbo",
    "pad_blur": "pbz",
    "pad_border_enabled": "pbre",
    "pad_border_color": "pbrc",
    "pad_border_opacity": "pbro",
    "pad_border_width": "pbrw",
    "pad_shadow": "psh",
    "pad_shadow_opacity": "psho",
    "pad_grid": "pg",
    "pad_grid_size": "pgs",
    "pad_grid_thickness": "pgt",
    "pad_grid_color": "pgc",
    "pad_grid_opacity": "pgo",
    "pad_crosshair": "pch",
    "pad_crosshair_color": "pchc",
    "pad_crosshair_opacity": "pcho",
    "pad_crosshair_size": "pchs",
    "pad_vignette": "pv",
    "pad_vignette_opacity": "pvo",
    "pad_clip_trail": "pct",

    # Cursor & clicks
    "show_cursor_dot": "cs",
    "cursor_dot_size": "cds",
    "cursor_dot_color": "cdc",
    "cursor_dot_opacity": "cdo",
    "show_clicks": "ck",
    "click_lifetime_ms": "cl",
    "click_radius": "cr",
    "click_line_width": "clw",
    "click_opacity": "cop",
    "click_expand": "cex",
    "click_style": "cst",

    # Stats / HUD
    "show_stats": "ss",
    "stats_opacity": "so",
    "stats_bg": "sbg",
    "stats_border": "sbr",
    "stats_show_speed": "ssv",
    "stats_show_peak": "ssp",
    "stats_show_cps": "ssc",
    "stats_show_clicks": "ssl",
    "stats_show_distance": "ssd",
    "stats_units": "sun",
    "stats_x_pct": "sxp",
    "stats_y_pct": "syp",
    "hud_show_avg_speed": "has",
    "chart_color": "chcl",

    # Canvas / source
    "canvas_aspect": "ca",
    "canvas_width": "cw",
    "canvas_height": "ch",
    "source_bg_enabled": "sbe",
    "source_bg_color": "sbc",
    "source_bg_opacity": "sbo",
    "overlay_opacity": "oo",

    # Motion
    "sensitivity": "sn",
    "view_mode": "vm",
    "camera_lag": "clg",
    "camera_look_ahead": "cla",
    "camera_follow": "cf",
    "view_zoom": "vz",
    "motion_scale": "ms",
    "motion_ease": "me",
    "motion_feel": "mf",
    "target_fps": "tf",
    "render_quality": "rq",
    "ws_send_hz": "whz",

    # Capture
    "capture_mode": "cm",
    "invert_y": "iy",

    # Nested dict sub-keys -> dot-notation alias strings
    "click_colors|left": "cl.l",
    "click_colors|right": "cl.r",
    "click_colors|middle": "cl.m",
    "click_colors|x1": "cl.x1",
    "click_colors|x2": "cl.x2",
    "click_show|left": "sh.l",
    "click_show|right": "sh.r",
    "click_show|middle": "sh.m",
    "click_show|side": "sh.s",
}

# Reverse map: alias -> full key path
REVERSE_SHARE_ALIASES: Dict[str, Any] = {v: k for k, v in SHARE_ALIASES.items()}


